FROM mcr.microsoft.com/dotnet/sdk:8.0 AS migrator

WORKDIR /app

COPY backend-dotnet/*.csproj ./
RUN dotnet restore
RUN dotnet tool install --global dotnet-ef
ENV PATH="${PATH}:/root/.dotnet/tools"

COPY backend-dotnet/. .

ENTRYPOINT ["dotnet", "ef", "database", "update"]
