name: Build Migrator Container
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

concurrency:
  group: BuildMigrator
  cancel-in-progress: true
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Up Dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.117

      - name: Run Unit Tests
        working-directory: backend-unittest
        run: |
          dotnet test

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile-Migrator
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            hodgeswt/cinemadle-migrator:latest
            hodgeswt/cinemadle-migrator:${{ github.run_number }}

