name: Run Unit Tests

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Set Up Dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.117
  
      - name: Run Unit Tests
        working-directory: backend-unittest
        run: |
          dotnet test
